/**
 * Add all your dependencies here. 
 * @require widgets/Viewer.js
 * @require plugins/LayerTree.js
 * @require plugins/LayerManager.js
 * @require plugins/OLSource.js
 * @require plugins/OSMSource.js
 * @require plugins/WMSCSource.js
 * @require plugins/ZoomToExtent.js
 * @require plugins/NavigationHistory.js
 * @require plugins/Zoom.js
 * @require plugins/AddLayers.js
 * @require plugins/RemoveLayer.js
 * @require RowExpander.js
 * @require OpenLayers/Request.js
 * @require plugins/MapBoxSource.js
 * @require plugins/MapQuestSource.js
 * @require plugins/BingSource.js
 * @require plugins/GoogleSource.js
 * @require overrides/override-ext-ajax.js
 * @require widgets/EmbedMapDialog.js
 * @require plugins/FeatureManager.js
 * @require plugins/FeatureEditor.js
 * @require plugins/Print.js  
 * @require plugins/Navigation.js 
 * @require plugins/NavigationHistory.js 
 * @require plugins/WMSGetFeatureInfo.js
 * @require plugins/Measure.js
 * @require plugins/ZoomToExtent.js 
 * @require plugins/Legend.js
 * @require plugins/GoogleEarth.js
 * @require plugins/LayerProperties.js
 * @require plugins/Styler.js
 * @require plugins/ZoomToLayerExtent.js
 * @require plugins/ZoomToSelectedFeatures.js
 * @require plugins/QueryForm.js
 * @require plugins/FeatureGrid.js
 * @require plugins/AddCategory.js
 * @require plugins/RenameCategory.js
 * @require plugins/RemoveCategory.js
 * @require widgets/ScaleOverlay.js
 * @require widgets/CrumbPanel.js
 * @require widgets/GoogleEarthPanel.js
 * @require widgets/NewSourceWindow.js
 * @require plugins/GeoNodeSource.js
 * @require plugins/PicasaFeedSource.js
 * @require plugins/YouTubeFeedSource.js
 * @require GeoExplorer.js
 * @require Composer.js
 * @require Viewer.js
 * @require GeoNode-mixin.js
 * @require GeoNode-GeoExplorer.js
 * 
 */
